apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongo-claimcheck.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mongo-claimcheck.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mongo-claimcheck.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mongo-claimcheck.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--bind_ip_all"]
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongo-claimcheck.fullname" . }}
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongo-claimcheck.fullname" . }}
                  key: mongo-root-password
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: {{ include "mongo-claimcheck.fullname" . }}