apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo-claimcheck.fullname" . }}
  labels:
    {{- include "mongo-claimcheck.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  selector:
    app.kubernetes.io/name: {{ include "mongo-claimcheck.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}