trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /Framework/Microservices/AppConfiguration
      - /service-deployment-template.yml
      - /HelmCharts/plain-app-chart

pool:
  vmImage: 'windows-latest'

extends:
  template: /service-deployment-template.yml
  parameters:
    solutionName: AppConfiguration
    pathToSolutionFolder: Framework/Microservices
    releaseName: appconfigmicroservice
    buildContext: Framework/Microservices/AppConfiguration  
    secureYml: mycai-appConfig-values.yml
