apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-pgvector.fullname" . }}
  labels:
    app: {{ include "postgres-pgvector.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgres-pgvector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres-pgvector.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.primary.image.repository }}:{{ .Values.primary.image.tag }}"
          imagePullPolicy: {{ .Values.primary.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            - name: postgres-data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
        - name: postgres-data
          {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "postgres-pgvector.fullname" . }}-pvc
          {{- end }}
