apiVersion: v1
kind: Service
metadata:
  name: {{ include "plain-app-chart.fullname" . }}
  labels:
    {{- include "plain-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.containerPorts }}
    - port: {{ .port }}
      name: {{ .name }}
      targetPort: {{ .name }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "plain-app-chart.selectorLabels" . | nindent 4 }}
